apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_ENDPOINT: "TU_ENDPOINT_RDS"
  DB_PORT: "3306"
  DB_NAME: "TU_DB"
  DB_USERNAME: "TU_USUARIO"
  DB_PASSWORD: "TU_PASSWORD"